# Mastering Scipy

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as spla
import scipy.sparse as spsp
import scipy.sparse.linalg as spspla

In [24]:
np.set_printoptions(suppress=True,precision=3)

In [25]:
cols = np.array([0,1,1,2,2,3,3,4,4,5,6,6,6,7,7])
rows = np.array([1,0,3,1,4,1,7,6,7,3,2,3,7,5,6])
data = np.array([1.,0.5,0.5,0.5,0.5,
                0.5,0.5,0.5,0.5,1.,
                1./3,1./3,1./3,0.5,0.5])

In [26]:
T = np.zeros((8,8));
T[rows,cols] = data

In [27]:
T

array([[0.   , 0.5  , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [1.   , 0.   , 0.5  , 0.5  , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.333, 0.   ],
       [0.   , 0.5  , 0.   , 0.   , 0.   , 1.   , 0.333, 0.   ],
       [0.   , 0.   , 0.5  , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.5  ],
       [0.   , 0.   , 0.   , 0.   , 0.5  , 0.   , 0.   , 0.5  ],
       [0.   , 0.   , 0.   , 0.5  , 0.5  , 0.   , 0.333, 0.   ]])

In [28]:
# from the transition matrix, we create a PageRank
# G = (1-p)*T + p*B
# B = m
# p = 0.15
G = (1-0.15)*T + 0.15/8
G

array([[0.019, 0.444, 0.019, 0.019, 0.019, 0.019, 0.019, 0.019],
       [0.869, 0.019, 0.444, 0.444, 0.019, 0.019, 0.019, 0.019],
       [0.019, 0.019, 0.019, 0.019, 0.019, 0.019, 0.302, 0.019],
       [0.019, 0.444, 0.019, 0.019, 0.019, 0.869, 0.302, 0.019],
       [0.019, 0.019, 0.444, 0.019, 0.019, 0.019, 0.019, 0.019],
       [0.019, 0.019, 0.019, 0.019, 0.019, 0.019, 0.019, 0.444],
       [0.019, 0.019, 0.019, 0.019, 0.444, 0.019, 0.019, 0.444],
       [0.019, 0.019, 0.019, 0.444, 0.444, 0.019, 0.302, 0.019]])

In [29]:
eigenvalues, eigenvectors = spla.eig(G)

In [30]:
print(eigenvalues)

[ 1.   +0.j    -0.655+0.j    -0.333+0.313j -0.333-0.313j -0.171+0.372j
 -0.171-0.372j  0.544+0.j     0.268+0.j   ]


In [31]:
print(eigenvectors)

[[-0.292+0.j    -0.499+0.j    -0.24 +0.225j -0.24 -0.225j  0.219+0.198j
   0.219-0.198j  0.516+0.j     0.272+0.j   ]
 [-0.576+0.j     0.769+0.j     0.023-0.353j  0.023+0.353j -0.261+0.113j
  -0.261-0.113j  0.66 +0.j     0.172+0.j   ]
 [-0.119+0.j     0.056+0.j     0.194-0.156j  0.194+0.156j -0.155-0.338j
  -0.155+0.338j -0.174+0.j     0.237+0.j   ]
 [-0.544+0.j    -0.242+0.j     0.529+0.j     0.529-0.j    -0.277-0.332j
  -0.277+0.332j -0.014+0.j    -0.674+0.j   ]
 [-0.097+0.j    -0.037+0.j    -0.231-0.018j -0.231+0.018j -0.252+0.292j
  -0.252-0.292j -0.136+0.j     0.376+0.j   ]
 [-0.213+0.j    -0.154+0.j    -0.2  +0.239j -0.2  -0.239j  0.153-0.111j
   0.153+0.111j -0.228+0.j    -0.373+0.j   ]
 [-0.254+0.j    -0.13 +0.j    -0.055+0.398j -0.055-0.398j  0.537+0.j
   0.537-0.j    -0.334+0.j     0.224+0.j   ]
 [-0.391+0.j     0.238+0.j    -0.019-0.334j -0.019+0.334j  0.036+0.179j
   0.036-0.179j -0.291+0.j    -0.235+0.j   ]]


In [32]:
PageRank = eigenvectors[:,0]
PageRank /= sum(PageRank) 

# what does /= mean? 
# x /= 3  -> x = x/3 


In [33]:
PageRank.real

array([0.117, 0.232, 0.048, 0.219, 0.039, 0.086, 0.102, 0.157])

The transition matrix is sparse: most of its entries are zeros. Sparse matrices with an extremely large size of special importance in Numerical Linear algebra, not only because they encode challenging scientific problems but also because it is extremely hard to manipulate them with basic algorithms       

## Creation of matrices and linear operators

Some different ways to construct a basic matrix as an ndarray, including an enumeration of all the special matrices already included in Numpy and Scipy. 

In [34]:
# constructing matrices in the matrix class 
C = np.matrix('1,2;4,6')
A = np.array([[1,2],[4,16]])
np.asmatrix(A)

matrix([[ 1,  2],
        [ 4, 16]])

In [38]:
E= spsp.rand(512,512, density=1).todense()
s_100_csc = spsp.rand(512,512, density=1, format='csc')
%timeit E.I

%timeit spspla.inv(s_100_csc)

9.62 ms ± 296 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
301 ms ± 11.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


We can always stack arrays in different ways: 

`numpy.contatenate((A1,A2, ...))` : join matrices together

`numpy.hstack((A1,A2, ...))` : stack matrices horizontally

`numpy.vstack((A1,A2, ...))` : stack matrices vertically

`numpy.tile(A,reps)` : repeat a matrix a certain number of times, given by `reps`

`scipy.linalg.block_diag(A1,A2,...)` : create a block diagonal array

In [56]:
A = np.array([[1,2],[3,4]])
b = np.tile(A,3)
b

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [75]:
spla.block_diag([[-3]*3[-4]*2,[-1]*4],[-1,0,1])

TypeError: 'int' object is not subscriptable

## Matrix factorizations related to solving matrix equations


The concept of matrix decomposition is what makes Numerical Linear Algebra an efficient tool in Scientific Computing.

If the matrix representing a problem is simple enough, any basic generic algorithms can find the solutions optimally. But, in real life, this situation seldom occurs.

What we do in the general case is finding a suitable matrix factorization and tailoring an algorithm that is optimal on each factor, thus gaining on each step an obvious advantage. 

Here we explore different factorization included in the modules, 
`scipy.linalg` and `scipy.sparse.linalg` that will help us achieve a robust solution to matrix equation. 

**Relevant Factorizations:**
1. Pivoted LU decomposition
2. Cholesky decomposition 
3. QR decomposition
4. Singular value decomposition


> In any case, mastering matrix equations with SciPy basically means identifying the matrices involved and choosing the most adequate algorithm in the libraries to perform the requested operations.

Besides being able to compute a solution with the least possible amount of roundoff error, we need to do so in the fastest possible way, and by using as few memory resources as possible. 

In [48]:

B_banded = np.zeros((2,6))
B_banded[0,1:] = -1
B_banded[1,:] = 2
print(B_banded)

spla.solveh_banded(B_banded,np.ones(6))

[[ 0. -1. -1. -1. -1. -1.]
 [ 2.  2.  2.  2.  2.  2.]]


array([3., 5., 6., 6., 5., 3.])

In [49]:
# test the Cholesky decomposition of matrix B 
B = spsp.diags([[-1]*5, [2]*6,[-1]*5],[-1,0,1]).todense()
print(B)

np.set_printoptions(suppress=True,precision=3)
print(spla.cholesky(B))
print(spla.cho_factor(B)[0])
print(spla.cholesky_banded(B_banded))

[[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]
[[ 1.414 -0.707  0.     0.     0.     0.   ]
 [ 0.     1.225 -0.816  0.     0.     0.   ]
 [ 0.     0.     1.155 -0.866  0.     0.   ]
 [ 0.     0.     0.     1.118 -0.894  0.   ]
 [ 0.     0.     0.     0.     1.095 -0.913]
 [ 0.     0.     0.     0.     0.     1.08 ]]
[[ 1.414 -0.707  0.     0.     0.     0.   ]
 [-1.     1.225 -0.816  0.     0.     0.   ]
 [ 0.    -1.     1.155 -0.866  0.     0.   ]
 [ 0.     0.    -1.     1.118 -0.894  0.   ]
 [ 0.     0.     0.    -1.     1.095 -0.913]
 [ 0.     0.     0.     0.    -1.     1.08 ]]
[[ 0.    -0.707 -0.816 -0.866 -0.894 -0.913]
 [ 1.414  1.225  1.155  1.118  1.095  1.08 ]]


# Scipy and Numpy: Optimizing and Boosting 

Numpy can operate with reasonable speeds on arrays containing $10^6$ elements.Once we go up to $10^7$ elements, operations can start to slow down and Python's memory will become limited, depending on the amount of RAM available.

> What is the best solution if you need to work with an array that is far larger - say, 10^10 elements? 

If these massive arrays primarily contain zeros, then you're in luck, as this is the property of sparse matrices. If a sparse matrix is treated correctly, operation time and memory usage can go down drastically. 

In [12]:
import numpy as np
from scipy.sparse.linalg import eigsh
from scipy.linalg import eigh
import scipy.sparse
import time

N = 3000
# Creating a random matrix 
m = scipy.sparse.rand(N,N)

# Creating an array clone to it 
a = m.toarray()

'''
You can determine the byte size of a numpy.array by calling its method nbytes 
To do the same with sparse matrices, you can use data.nbytes
'''

print('Numpy array data size ' + str(a.nbytes/1000000) + ' megabytes')
print('The sparse matrix data size: ' + str(m.data.nbytes/1000000.00) + ' megabytes')

# Non-sparse
t0 = time.time()
res1 = eigh(a)
dt = str(np.round(time.time()- t0, 3)) + ' seconds'
print('Non-sparse operation takes ' + dt)

# Sparse 
t0 = time.time()
res2 = eigsh(m)
dt = str(np.round(time.time()-t0,3)) + ' seconds'
print('Sparse operation takes ' + dt)

Numpy array data size 72.0 megabytes
The sparse matrix data size: 0.72 megabytes
Non-sparse operation takes 4.697 seconds
Sparse operation takes 0.083 seconds


In [83]:
psi = np.zeros((2,2))
H = np.zeros((2,2,2,2))
h_11 = H[0,0,:,:]
V = H[0,1]

def mdot(operator,psi):
    return operator.transpose(0,2,1,3).reshape(4,4).dot(psi.reshape(4)).reshape(2,2)

In [84]:
mdot(H,psi)

array([[0., 0.],
       [0., 0.]])

In [85]:
V

array([[0., 0.],
       [0., 0.]])

In [86]:
H

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [87]:
psi

array([[0., 0.],
       [0., 0.]])

In [103]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [105]:
c = np.ones_like(b)
c

array([1., 1., 1., 1., 1.])

In [106]:
spla.hilbert(5)

array([[1.   , 0.5  , 0.333, 0.25 , 0.2  ],
       [0.5  , 0.333, 0.25 , 0.2  , 0.167],
       [0.333, 0.25 , 0.2  , 0.167, 0.143],
       [0.25 , 0.2  , 0.167, 0.143, 0.125],
       [0.2  , 0.167, 0.143, 0.125, 0.111]])